[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#e6efff"
yellow = "#d19a66"

[colors.normal]
black = "#1e2127"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#828791"
yellow = "#d19a66"

[colors.primary]
background = "#1e2127"
foreground = "#abb2bf"
bright_foreground = "#e6efff"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "FiraMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "FiraMonoNerdFont"
style = "Italic"

[font.italic]
family = "FiraMonoNerdFont"
style = "Italic"

[font.normal]
family = "FiraMonoNerdFont"
style = "Regular"

[window]
decorations = "full"
dynamic_title = true
opacity = 0.96
title = "Alacritty"

[window.dimensions]
columns = 200
lines = 46
